#if !defined(AFX_DEVICES1_H__164BFA7D_BB67_4771_A3A7_AA9B7D933125__INCLUDED_)
#define AFX_DEVICES1_H__164BFA7D_BB67_4771_A3A7_AA9B7D933125__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDevices wrapper class

class CDevices : public COleDispatchDriver
{
public:
	CDevices() {}		// Calls COleDispatchDriver default constructor
	CDevices(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDevices(const CDevices& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	LPDISPATCH GetItem(const VARIANT& Key);
	short FindDevice(LPCTSTR strDeviceName);
	CString FindDeviceName(short index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DEVICES1_H__164BFA7D_BB67_4771_A3A7_AA9B7D933125__INCLUDED_)
