//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Pathology.rc
//
#define IDD_ABOUTBOX                    100
#define IDM_MY_EDIT                     102
#define IDR_MAINFRAME                   128
#define IDR_CPI_RETYPE                  129
#define IDB_BITMAP_PICTURE              130
#define IDD_DIALOG_MEDPERSON            131
#define IDD_DIALOG_MEDDIAGNOSE          132
#define IDD_DIALOG_MEDIMAGE             133
#define IDD_DIALOG_RECORDING            134
#define IDB_IMAGELIST                   135
#define IDB_FILETYPE_BMP                136
#define IDB_FILETYPE_JPG                137
#define IDB_FILETYPE_TIF                138
#define IDB_RECYCLE                     139
#define IDB_MULTI_DOC                   140
#define IDD_DIALOG_DBLIST               141
#define IDB_SINGLE_DOC                  142
#define IDC_CURSOR_HANDON               143
#define IDB_BITMAP_TOOLBARGRAY          144
#define IDD_PATHOLOGY_FORM              145
#define IDD_DIALOG_MEDSOUND             146
#define IDR_MAINFRAME_SMALL             147
#define IDR_MAINFRAME_SMALL_GRAY        148
#define IDB_BITMAP_MIC                  149
#define IDB_BITMAP_STOP                 150
#define IDB_BITMAP_PHOTO                151
#define IDB_IMGLIST_TAB                 152
#define IDR_TOOLBAR_DBLIST              153
#define IDC_CURSOR_RECTIFY              154
#define IDI_ICON_STATISTIC              155
#define IDR_TOOLBAR_STATISTIC           156
#define IDD_DIALOG_AREAOUT              157
#define IDD_DIALOG_LISTINPUT            158
#define IDD_StrEdit                     159
#define IDD_DIALOG_COMPOSITEQUERY       160
#define IDB_BITMAP_HISIDIN              161
#define IDB_ICON_CHARGEDETAIL           162
#define IDR_TOOLBAR_CHARGEDETAIL        163
#define IDD_DIALOG_SFDETAIL             164
#define IDD_RECORD_INFO                 165
#define IDB_BITMAP_WAV                  166
#define IDI_ICON_STOPPREVIEW            167
#define IDI_ICON_STOPPRINT              168
#define IDD_NORMALWORD                  169
#define IDD_SECECTBZ                    170
#define IDD_NUMINPUT                    171
#define IDD_BuweiBZ                     172
#define IDD_Edit_Report                 173
#define IDD_ZHENDUAN                    174
#define IDD_DIALOG_XGYJ                 175
#define IDD_DIALOG_BDBG                 176
#define IDB_ROTATE90                    177
#define IDD_DIALOG_SFJG                 178
#define IDD_DIALOG_KLHZ                 179
#define IDB_ROTATE180                   180
#define IDI_ICON_ENROLL                 181
#define IDD_DIALOG_HISTORY              182
#define IDD_DIALOG_WAX                  183
#define IDD_DIALOG_PRESLICE             184
#define IDB_FLIPVERT                    185
#define IDD_DIALOG_ADVICE               186
#define IDB_FLIPHORI                    187
#define IDD_DIALOG_BQLB                 188
#define IDD_DIALOG_SYSCONFIG            189
#define IDR_TOOLBAR_DRAWBAR             190
#define IDD_DIALOG_TAG                  191
#define IDD_DIALOG_TJYZ                 192
#define IDR_MENU_PICPROCESS             193
#define IDD_DIALOG_REFLECTION           194
#define IDD_DIALOG_ROTATION             195
#define IDD_DIALOG_RESIZE               196
#define IDD_DIALOG_REALTIMEADVICE       197
#define IDC_COMBO_FONTNAME              198
#define IDD_DIALOG_DBSELECT             199
#define IDD_DIALOG_QUICKQUERY           200
#define IDB_BITMAP_KEY                  201
#define IDB_BITMAP_PERSON               202
#define IDD_DIALOG_BPSMHD               203
#define IDB_BITMAP_PRINT                204
#define IDD_DIALOG_FMTSELECT            205
#define IDC_COMBO_FONTSIZE              206
#define IDR_MENU_IMAGEPROCESSING        207
#define IDB_ROTATE270                   208
#define IDC_BUTTON_COLORTEXT            209
#define IDI_ICON_SECURITY               210
#define IDD_DIALOG_PICNOTE              211
#define IDC_CHK_FONTSTYLE_BOLD          212
#define IDI_ICON_ADD                    213
#define IDC_CHK_FONTSTYLE_ITALIC        214
#define IDC_CHK_FONTSTYLE_UNDERLINE     215
#define IDC_CHK_MULTILINE               216
#define IDC_BUTTON_LINE_TYPE            217
#define IDC_BUTTON_LINE_WIDTH           218
#define IDC_LEFT                        219
#define IDC_BUTTON_LINE_COLOR           220
#define IDD_DIALOG_MEASURE              221
#define IDR_TOOLBAR_PSMANAGE            222
#define IDC_CENTER                      223
#define IDC_CURSOR_MAGIC                224
#define IDC_RIGHT                       225
#define IDC_TOP                         226
#define IDC_MIDDLE                      227
#define IDC_BOTTOM                      228
#define IDC_EDIT_CONTENT                229
#define IDD_PROPERTY_LINE               230
#define IDD_PROPERTY_TEXT               231
#define IDD_DIALOG_STANDARD             232
#define IDD_DIALOG_DINGBIAO             233
#define IDD_DIALOG_HZLB                 234
#define IDD_DIALOG_SFLB                 235
#define IDD_DIALOG_SECURITY             236
#define IDD_DIALOG_NEWUSER              237
#define IDD_DIALOG_TBS                  238
#define IDD_DIALOG_GETCODE              239
#define IDD_DIALOG_PROGRESSBAR          240
#define IDD_DLG_ADJUST                  241
#define IDD_DLG_GAMMA                   242
#define IDD_DLG_WB                      243
#define IDD_DIALOG_EQUAL                244
#define IDD_DIALOG_STATISTIC            245
#define ID_DELETE                       246
#define IDMANAGE                        247
#define IDPASS                          248
#define ID_ADJUST_RESET                 249
#define ID_WB_RATIO                     250
#define ID_ADJUST_DEFAULT               251
#define ID_WB_SET                       252
#define ID_GET                          253
#define ID_DELETE_ALL                   254
#define IDC_PROPERTY_GRID               255
#define CG_IDR_POPUP_DBF_STANDARD       256
#define IDD_DIALOG_PASSMANAGE           257
#define IDD_DIALOG_BATCHPRINT           258
#define IDB_IMGLIST_VIEW                259
#define IDD_DIALOG_FIELDSELECT          260
#define IDD_DIALOG_PASSINPUT            261
#define IDR_POPUP_TREE                  262
#define IDB_ORIG                        263
#define IDD_DIALOG_BCBG                 264
#define IDD_DIALOG_MEDMATERIAL          265
#define IDD_DIALOG_QCMX                 266
#define IDD_DIALOG_SLICE                267
#define IDD_DIALOG_JSYZ                 268
#define IDD_DIALOG_QPPJ                 269
#define IDD_DIALOG_SELFDEFINE           270
#define IDD_RECORD_SELF                 271
#define IDD_DIALOG_LOGO                 272
#define IDD_DIALOG_TEXT                 273
#define IDB_BITMAP_SECURITY             274
#define IDD_DIALOG_NOTEPAD              275
#define IDD_DIALOG_KNLY                 276
#define IDD_DIALOG_DSHOW                277
#define IDD_DIALOG_DBTYPE               278
#define IDD_DIALOG_BDSEL                279
#define IDD_DIALOG_FALSENOQUERY         280
#define IDB_BITMAP_VIDEO                282
#define IDB_BITMAP_MOVIE                283
#define IDD_DIALOG_MOVIEWND             284
#define IDB_BITMAP_VIDEOIN              285
#define IDB_BITMAP_IMGCAP               286
#define IDD_DIALOG_CKYJ                 287
#define IDR_TOOLBAR_TRANSTABLE          288
#define IDD_DIALOG_QPYJ                 289
#define IDD_DIALOG_GZDDY                290
#define IDD_DIALOG_ZPQK                 291
#define IDD_DIALOG_NOTIFY               292
#define IDD_DIALOG_BBMCDETAIL           293
#define IDD_DIALOG_MVC300STP            294
#define IDB_BITMAP_PRINTER              295
#define IDD_DIALOG_CHARGECONFORM        296
#define IDD_DIALOG_ZDEX                 297
#define IDD_DIALOG_CGSFQR               298
#define IDR_TOOLBAR_REPORT              299
#define IDD_DIALOG_TIMEQUERY            301
#define IDD_DIALOG_BDYY                 302
#define IDD_DIALOG_ZCSFQR               303
#define IDD_DIALOG_DEVICES              307
#define IDD_DIALOG_PROPERTY             308
#define IDD_DIALOG_STREAM               309
#define IDD_DIALOG_YQJL                 310
#define IDD_DIALOG_INPUT                311
#define IDD_DIALOG_LeaveMessage         312
#define IDD_DIALOG1                     313
#define IDD_DIALOG_BookingTip           314
#define IDR_MENU_SLICE                  314
#define IDR_MENU_REPORTVIEW             315
#define IDD_DIALOG_QPSMBATCH            316
#define IDR_MENU_MATERIAL               317
#define IDD_DIALOG_QCYZBZ               318
#define IDD_DIALOG_1                    319
#define IDD_DIALOG_NOUSE                319
#define IDD_DIALOG_PICNOTEMAINTENANCE   320
#define IDD_DIALOG_AdviceTip            321
#define IDD_DIALOG_DELETEREASON         322
#define IDD_DIALOG_MicroWriterConfig    323
#define IDD_DIALOG_GOWAX                330
#define IDD_DIALOG_LKBS                 331
#define IDB_BITMAP_DOWN                 332
#define IDD_CAPTURE_CANON_S5            334
#define IDD_PROGRESS                    335
#define IDC_TAB_CTRL                    1004
#define IDC_STATIC_VALUE                1005
#define IDC_STATIC_MSG                  1006
#define IDC_LEDTEXT                     1007
#define IDC_BUTTON_RECORD               1008
#define IDC_BUTTON_STOP                 1009
#define IDC_BUTTON_PHOTO                1010
#define IDC_FLATTABCTRL                 1011
#define IDC_EDIT_START                  1012
#define IDC_EDIT2                       1013
#define IDC_EDIT_END                    1014
#define IDC_EDIT_DTGAIN                 1014
#define IDINDEX                         1015
#define IDC_EDIT_TIME                   1015
#define IDC_EDIT_FROM                   1016
#define IDC_EDIT_TO                     1017
#define IDC_STATIC_FROM                 1018
#define IDC_EDIT_PS1                    1019
#define IDC_EDIT_NAME                   1020
#define IDC_SB_GAIN                     1021
#define IDC_TEXT_GAIN                   1022
#define IDC_SB_HBLANKING                1023
#define IDC_SB_VBLANKING                1024
#define IDC_EDIT_HEIGHT                 1025
#define IDC_EDIT_HEIGHTRATE             1026
#define IDC_COMBO_CONTENT               1027
#define IDC_SLIDER_BRIGHTNESS           1028
#define IDC_STATIC_RECORDLIST           1029
#define IDC_STATIC_BRIGHTNESS           1030
#define IDC_EDIT_RED_RATIO              1031
#define IDC_EDIT_GREEN_RATIO            1032
#define IDC_EDIT_BLUE_RATIO             1033
#define IDC_SLIDER_RED                  1034
#define IDC_STATIC_SJDW                 1035
#define IDC_SLIDER_GREEN                1036
#define IDC_STATIC_GREEN                1037
#define IDC_CM_GAIN                     1038
#define IDC_CM_ADC                      1039
#define IDC_CM_BAYER                    1040
#define IDC_STATIC_LCZD                 1041
#define IDC_STATIC_BSZY                 1042
#define IDC_GAMMA_RATIO                 1043
#define IDC_COMBOBOXEX1                 1044
#define IDC_STATIC_SQH                  1045
#define IDC_LIST1                       1046
#define IDC_EDIT_ORDERTYPE              1047
#define IDC_LIST2                       1048
#define IDC_EDIT_BLH                    1049
#define IDC_LIST3                       1050
#define IDC_EDIT_XM                     1051
#define IDC_LIST4                       1052
#define IDC_EDIT_HF                     1053
#define IDC_SITE                        1054
#define IDC_BUTTON8                     1055
#define IDC_EDIT_LXDZ                   1056
#define IDC_ENROLL                      1057
#define IDC_EDIT_SJDW                   1058
#define IDC_EDIT_BQ                     1059
#define IDC_EDIT_BBMC                   1060
#define IDC_EDIT_FB                     1061
#define IDC_EDIT_LCZD                   1062
#define IDC_EDIT_BSZY                   1063
#define IDC_EDIT_SSSJ                   1064
#define IDC_STATIC_YBH                  1065
#define IDC_STATIC_XB                   1066
#define IDC_STATIC_ZY                   1067
#define IDC_STATIC_SJKS                 1068
#define IDC_STATIC_CH                   1069
#define IDC_STATIC_SF                   1070
#define IDC_EDIT_SQH                    1071
#define IDC_EDIT_YBH                    1072
#define IDC_EDIT_XB                     1073
#define IDC_EDIT_ZY                     1074
#define IDC_EDIT_SJKS                   1075
#define IDC_EDIT_CH                     1076
#define IDC_EDIT_AGE1                   1076
#define IDC_EDIT_SF                     1077
#define IDC_EDIT_AGE2                   1077
#define IDLISTVIEW                      1078
#define IDC_STATIC_BRID                 1079
#define IDC_STATIC_MZH                  1080
#define IDC_STATIC_NL                   1081
#define IDC_STATIC_JG                   1082
#define IDC_STATIC_LXDH                 1082
#define IDC_STATIC_MCYJ                 1083
#define IDC_STATIC_SJYS                 1084
#define IDC_STATIC_BBLX                 1085
#define IDC_STATIC_BHGYY                1086
#define IDC_STATIC_QCYS                 1087
#define IDC_EDIT_BRID                   1088
#define IDC_EDIT_MZH                    1089
#define IDC_EDIT_NL                     1090
#define IDC_EDIT_JG                     1091
#define IDC_EDIT_LXDH                   1091
#define IDC_EDIT_MCYJ                   1092
#define IDC_EDIT_SJYS                   1093
#define IDC_BUTTON1                     1094
#define IDC_STATIC_CSRQ                 1094
#define IDC_EDIT_BBLX                   1095
#define IDC_BUTTON_COPYZZ               1095
#define IDC_BUTTON2                     1096
#define IDC_EDIT_BHGYY                  1097
#define IDC_BUTTON3                     1098
#define IDC_EDIT_QCYS                   1099
#define IDC_BUTTON4                     1100
#define IDC_STATIC_BDH                  1101
#define IDC_STATIC_INFO                 1102
#define IDC_STATIC_ZYH                  1103
#define IDC_BUTTON6                     1104
#define IDC_STATIC_MZ                   1105
#define IDC_BUTTON7                     1106
#define IDC_STATIC_SFZH                 1107
#define IDC_DATE_SJRQ                   1108
#define IDC_STATIC_JJ                   1109
#define IDC_STATIC_SJRQ                 1110
#define IDC_STATIC_BBQS                 1111
#define IDC_STATIC_SJRQ2                1111
#define IDC_STATIC_QCRQ                 1112
#define IDC_EDIT_BDH                    1113
#define IDC_EDIT_ZYH                    1114
#define IDC_EDIT_MZ                     1115
#define IDC_EDIT_SFZH                   1116
#define IDC_EDIT_JJ                     1117
#define IDC_STATIC_BBQK                 1118
#define IDC_EDIT_BBQK                   1119
#define IDC_EDIT_BBQS                   1120
#define IDC_DATE_QCRQ                   1121
#define IDC_EDIT_NLDW                   1122
#define IDC_HISID_EXTRACT               1123
#define IDC_SF_DETAIL                   1124
#define IDC_STATIC_FIELD                1125
#define IDC_EDIT_CSRQ                   1125
#define IDC_STATIC_PROMPT1              1126
#define IDC_STATIC_PROMPT2              1127
#define IDC_STATIC_RYSJ                 1128
#define IDC_EDIT_RYSJ                   1129
#define IDC_STATIC_GJSJ                 1130
#define IDC_EDIT_GJSJ                   1131
#define IDC_STATIC_ZDYJ                 1132
#define IDC_EDIT_ZDYJ                   1133
#define IDC_STATIC_ZDBM                 1134
#define IDC_COMBO_WORD                  1135
#define IDC_ADDINFO                     1136
#define IDC_EDIT_SFYX                   1137
#define IDC_STATIC_ZZYS                 1138
#define IDC_EDIT_ZZYS                   1139
#define IDC_STATIC_ZDFH                 1140
#define IDC_EDIT_ZDFH                   1141
#define IDC_STATIC_SHYS                 1142
#define IDC_EDIT_SHYS                   1143
#define IDC_STATIC_CZYS                 1144
#define IDC_EDIT_CZYS                   1145
#define IDC_DATE_BGRQ                   1146
#define IDC_STATIC_ZDGJC                1147
#define IDC_EDIT_ZDGJC                  1148
#define IDC_TREE_BWMX                   1149
#define IDC_TREE_RYSJ                   1150
#define IDC_TREE_ZDYJ                   1151
#define IDC_TREE_GJSJ                   1152
#define IDC_STATIC_BWBZ                 1153
#define IDC_EDIT_FBCK                   1154
#define IDC_STATIC_FBCK                 1155
#define IDC_BUTTON_BDBG                 1156
#define IDC_BUTTON_QCMX                 1157
#define IDC_BUTTON_XGYJ                 1158
#define IDC_BUTTON_JSYZ                 1159
#define IDC_BUTTON_TJYZ                 1160
#define IDC_BUTTON_BCBG                 1161
#define IDC_ZQM                         1162
#define IDC_BUTTON_KNHZ                 1163
#define IDC_BUTTON_QPPJ                 1164
#define IDC_BUTTON_SFJG                 1165
#define IDC_BUTTON_CYC                  1166
#define IDC_BUTTON_ZDMB                 1167
#define IDC_BUTTON_BGCHECK              1168
#define IDC_BUTTON_BC                   1169
#define IDC_BUTTON_NEWSAMPLE            1169
#define IDC_BUTTON_TQZD                 1170
#define IDC_BUTTON_WAX                  1171
#define IDC_BUTTON_PRINT                1172
#define IDC_BUTTON_SAVE                 1173
#define IDC_BUTTON_START                1174
#define IDC_EDIT_XGYJ                   1175
#define IDC_STATIC_CZYJ                 1176
#define IDC_STATIC_XGYJ                 1177
#define IDC_STATIC_BDJG                 1178
#define IDC_EDIT_HZYJ                   1179
#define IDC_EDIT_BDJG                   1180
#define IDC_STATIC_XGYJ2                1181
#define IDC_STATIC_BDBGYS               1182
#define IDC_EDIT_BDBGYS                 1183
#define IDC_STATIC_BDBGRQ               1184
#define IDC_DATE_BDBGRQ                 1185
#define IDC_STATIC_BDFH                 1186
#define IDC_EDIT_BDFH                   1187
#define IDC_STATIC_BDSHYS               1188
#define IDC_EDIT_BDSHYS                 1189
#define IDC_STATIC_BCZD                 1190
#define IDC_EDIT_BCZD                   1191
#define IDC_STATIC_BCBGYS               1192
#define IDC_STATIC_                     1193
#define IDC_EDIT_BCBGYS                 1194
#define IDC_STATIC_BCBGRQ               1195
#define IDC_DATE_BCBGRQ                 1196
#define IDC_STATIC_JHSFSJ               1197
#define IDC_STATIC_SFYS                 1198
#define IDC_EDIT_SFYS                   1199
#define IDC_DATE_JHSFSJ                 1200
#define IDC_STATIC_SFJG                 1201
#define IDC_EDIT_SFJG                   1202
#define IDC_BUTTON_BLH                  1203
#define IDC_SPIN_BLH                    1204
#define IDC_BUTTON_REFRESH              1205
#define IDC_EDIT_HZFQR                  1206
#define IDC_STATIC_CYYS                 1207
#define IDC_STATIC_HZRQ                 1208
#define IDC_DATE_HZRQ                   1209
#define IDC_EDIT_CYYS                   1210
#define IDC_STATIC_ZJYJ                 1211
#define IDC_EDIT_ZJYJ                   1212
#define IDC_STATIC_WYYJ                 1213
#define IDC_EDIT_WYYJ                   1214
#define IDC_STATIC_HLYJ                 1215
#define IDC_STATIC_YSYJ                 1216
#define IDC_EDIT_YSYJ                   1217
#define IDC_COMBO_RWLY                  1218
#define IDC_COMBO_QPZH                  1219
#define IDC_STATIC_XH                   1220
#define IDC_COMBO_QPSM                  1221
#define IDC_COMBO_ZPR                   1222
#define IDC_STATIC_QCBW                 1223
#define IDC_STATIC_WFYY                 1224
#define IDC_STATIC_CKS                  1225
#define IDC_EDIT_WFYY                   1226
#define IDC_STATIC_LKZS                 1227
#define IDC_HYP_BQLB                    1228
#define IDC_EDIT_LKZS                   1229
#define IDC_HYP_KNLY                    1230
#define IDC_HYP_SFBL                    1231
#define IDC_EDIT_CKZS                   1232
#define IDC_STATIC_BMXX                 1233
#define IDC_EDIT_QCFY                   1234
#define IDC_BUTTON_QPQR                 1235
#define IDC_EDIT_BBWZ                   1236
#define IDC_DATE_BMRQ                   1237
#define IDC_EDIT_QCJLR                  1238
#define IDC_HYP_BQXX                    1239
#define IDC_STATIC_LKH                  1240
#define IDC_COMBO_LKH                   1241
#define IDC_STATIC_QPS                  1242
#define IDC_STATIC_BZ                   1243
#define IDC_STATIC_JSYZ                 1244
#define IDC_EDIT_QPS                    1245
#define IDC_STATIC_SQRQ                 1246
#define IDC_DATE_SQRQ                   1247
#define IDC_BUTTON_YZZH                 1248
#define IDC_COMBO_YZZT                  1249
#define IDC_COMBO_YZLX                  1250
#define IDC_STATIC_YZXX                 1251
#define IDC_STATIC_QPRQ                 1252
#define IDC_DATE_QPRQ                   1253
#define IDC_CHECK_NOTPRINT              1254
#define IDC_BUTTON_BQDY                 1255
#define IDC_PLACEHOLDER                 1256
#define IDC_BUTTON_BPSMHD               1257
#define IDC_STATIC_TAGLIST              1258
#define IDC_EDIT_BJW                    1259
#define IDC_BUTTON_ADDBJW               1260
#define IDC_BUTTON_ADDTC                1261
#define IDC_COMBO_TC                    1262
#define IDC_STATIC_YZLX                 1263
#define IDC_COMBO_TB                    1264
#define IDC_RADIO_HORIZONTAL            1265
#define IDC_RADIO_VERTICAL              1266
#define IDC_RADIO_HORI_VERTI            1267
#define IDC_RADIO_RIGHT_ANGLE           1268
#define IDC_RADIO_STRAIGHT_ANGLE        1269
#define IDC_RADIO_LEFT_ANGLE            1270
#define IDC_RADIO_ANGLE                 1271
#define IDC_EDIT_ANGLE                  1272
#define IDC_SPIN_ANGLE                  1273
#define IDC_STATIC_IMAGE1               1274
#define IDC_STATIC_IMAGE2               1275
#define IDC_STATIC_TJXM                 1276
#define IDC_STATIC_QPPJ                 1277
#define IDC_BUTTON_PD                   1278
#define IDC_RADIO_1                     1279
#define IDC_RADIO_2                     1280
#define IDC_RADIO_3                     1281
#define IDC_DATE_SJRQ_FROM              1282
#define IDC_DATE_SJRQ_TO                1283
#define IDC_CHECK_SJRQ                  1284
#define IDC_DATE_BGRQ_FROM              1285
#define IDC_DATE_BGRQ_TO                1286
#define IDC_CHECK_BGRQ                  1287
#define IDC_COMBO_BGZT                  1288
#define IDC_HYP_NOTE                    1289
#define IDC_CHECK_JBMYD1                1290
#define IDC_CHECK_JBMYD2                1291
#define IDC_CHECK_JBMYD3                1292
#define IDCOPY                          1293
#define IDC_RADIO1                      1294
#define IDC_RADIO2                      1295
#define IDC_CHECK_YZFY2                 1296
#define IDC_BUTTON_MICD10               1297
#define IDC_CHECK_LZXB                  1298
#define IDC_CHECK_JGXB                  1299
#define IDC_CHECK_HSXB                  1300
#define IDC_CHECK_DCGR                  1301
#define IDC_CHECK_MJGR                  1302
#define IDC_CHECK_LZJGR                 1303
#define IDC_CHECK_FXJGR                 1304
#define IDC_CHECK_HPVGR                 1305
#define IDC_CHECK_BZBDGR                1306
#define IDC_CHECK_QGJGR                 1307
#define IDC_CHECK_LSRTZBDGR             1308
#define IDC_EDIT_PS2                    1309
#define IDC_PROGRESS_BAR                1310
#define IDC_RECYCLE                     1311
#define IDC_LIST_THUMBNAIL              1312
#define IDC_COMBO_USER                  1313
#define IDC_STATIC_TO                   1314
#define IDC_EDIT_PASSWORD               1315
#define IDC_EDIT1                       1316
#define IDC_EDIT_LENGTH                 1317
#define IDC_EDIT_BUFFERPATH             1318
#define IDC_COMBO_FIELD                 1319
#define IDC_EDIT_BZ                     1320
#define IDC_EDIT_XFIELD                 1321
#define IDC_EDIT_ZOOM                   1322
#define IDC_EDIT_YFIELD                 1323
#define IDC_COMBO_OPERATOR              1324
#define IDC_EDIT_FOCUSX                 1325
#define IDC_COMBO_UNIT                  1326
#define IDC_EDIT_FOCUSW                 1327
#define IDC_EDIT_OTHERINFO              1328
#define IDC_EDIT_FOCUSY                 1329
#define IDC_BUTTON_STOPPREVIEW          1330
#define IDC_EDIT_FOCUSH                 1331
#define IDC_BUTTON_AND                  1332
#define IDC_EDIT_MTX                    1333
#define IDC_BUTTON_STOPPRINT            1334
#define IDC_EDIT_MTW                    1335
#define IDC_BUTTON_OR                   1336
#define IDC_EDIT_MTY                    1337
#define IDC_EDIT_QUERY                  1338
#define IDC_EDIT_MTH                    1339
#define IDC_BUTTON_ADD                  1340
#define IDC_BUTTON_MODIFY               1341
#define IDC_BUTTON_SELBJW               1342
#define IDC_BUTTON_CLEAR                1343
#define IDC_BUTTON_CANCEL               1344
#define IDC_BUTTON_TBBJW                1345
#define IDC_BUTTON_DELETE               1346
#define IDC_SLIDER_CONTRAST             1347
#define IDC_STATIC_ORDERTYPE            1348
#define IDC_STATIC_QCXX                 1349
#define IDC_STATIC_BLH                  1350
#define IDC_EDIT_WIDTH                  1351
#define IDC_STATIC_CONTRAST             1352
#define IDC_STATIC_XM                   1353
#define IDC_STATIC_YZZT                 1354
#define IDC_SLIDER_GAMMA                1355
#define IDC_STATIC_HF                   1356
#define IDC_EDIT_WIDTHRATE              1357
#define IDC_STATIC_GAMMA                1358
#define IDC_STATIC_LXDZ                 1359
#define IDC_CHECK_DISTORT               1360
#define IDC_STATIC_RED                  1361
#define IDC_STATIC_BQ                   1362
#define IDC_STATIC_BBMC                 1363
#define IDC_STATIC1                     1364
#define IDC_SLIDER_BLUE                 1365
#define IDC_STATIC_FB                   1366
#define IDC_STATIC_BLUE                 1367
#define IDC_STATIC2                     1368
#define IDC_EDIT_TINT_UPPER             1369
#define IDC_STATIC_SSSJ                 1370
#define IDC_EDIT_TINT_LOWER             1371
#define IDC_EDIT_HBLANKING              1372
#define IDC_EDIT_VBLANKING              1373
#define IDC_COMBO_METHOD                1374
#define IDC_EDIT_FACTOR                 1375
#define IDC_LIST_DBF                    1376
#define IDC_LIVE_FINGER                 1377
#define IDC_MSG                         1378
#define IDC_FUNCTION                    1379
#define IDC_EDIT_BLZD                   1380
#define IDC_STATIC_NAME                 1381
#define IDC_BUTTON5                     1382
#define IDC_STATIC_TIME                 1383
#define IDC_NOTE                        1384
#define IDC_EDIT_ZDBM                   1385
#define IDC_STATIC_SFYX                 1386
#define IDC_BUTTON_NEW                  1387
#define IDC_BUTTON_HXZD                 1388
#define IDC_EDIT_CZYJ                   1389
#define IDC_STATIC_HZFQR                1390
#define IDC_STATIC_BGGS                 1391
#define IDC_COMBO_BGGS                  1392
#define IDC_EDIT_CKS                    1393
#define IDC_HYP_LSJC                    1394
#define IDC_HYP_BDYY                    1395
#define IDC_TEXT_LKZS                   1396
#define IDC_BUTTON_QUERY                1397
#define IDC_CHECK_SELECTALL             1398
#define IDC_HYP_HZBL                    1399
#define IDC_STATIC_CKZS                 1400
#define IDC_BUTTON_CKHD                 1401
#define IDC_TEXT_CKZS                   1402
#define IDC_BUTTON_BMQR                 1403
#define IDC_STATIC_QCFY                 1404
#define IDC_TEXT_QCFY                   1405
#define IDC_STATIC_BMRQ                 1406
#define IDC_STATIC_BBWZ                 1407
#define IDC_TEXT_BBWZ                   1408
#define IDC_STATIC_QPXX                 1409
#define IDC_STATIC_QCJLR                1410
#define IDC_TEXT_QCJLR                  1411
#define IDC_BUTTON_BQZX                 1412
#define IDC_COMBO_DB                    1413
#define IDCONFORM                       1414
#define IDC_EDIT_CODE                   1415
#define IDC_CHECK_XBL1                  1416
#define IDC_CHECK_XBL2                  1417
#define IDC_CHECK_YZFY1                 1418
#define IDC_COMBO_FMT                   1419
#define IDC_CHECK_YZFY3                 1420
#define IDC_BUTTON_SICD10               1421
#define IDC_LIST_DBDEFINE               1422
#define IDC_LIST_SELFDEFINE             1423
#define IDC_BUTTON_SEL                  1424
#define IDC_BUTTON_UNSEL                1425
#define IDDELETE                        1426
#define IDC_STATIC_START                1427
#define IDC_DATE_START                  1428
#define IDC_DATE_END                    1430
#define IDC_STATIC_END                  1431
#define IDNEW                           1432
#define IDC_EDIT_INFO                   1433
#define IDC_STATIC_DATABASE             1434
#define IDC_STATIC_PERSON               1435
#define IDC_STATIC_KEY                  1436
#define IDC_EDIT_EX_BLH                 1437
#define ID_SEND                         1438
#define ID_CLEAR                        1439
#define IDC_COMBO_PERSON                1440
#define IDC_CHECK_NOTHD                 1441
#define IDC_COMBO_XH                    1442
#define IDC_EDIT_QCBW                   1443
#define IDC_COMBO_DEVICE                1444
#define IDC_COMBO_FORMAT                1445
#define IDC_COMBO_VIDEOINPUT            1446
#define IDC_COMBO_BLH                   1447
#define IDINSERT                        1448
#define IDC_STATIC_QPZS                 1449
#define IDC_CHECK_YQBG                  1450
#define IDC_CHECK_BDBG                  1451
#define IDEXPORT                        1452
#define IDQUERY                         1453
#define IDC_EDIT_QUERYRESULT            1454
#define IDC_STATIC_R                    1455
#define IDC_STATIC_RWLY                 1456
#define IDC_STATIC_QPZH                 1457
#define IDC_STATIC_QPSM                 1458
#define IDC_STATIC_ZPR                  1459
#define IDC_STATIC_ZPSJ                 1460
#define IDC_DATE_ZPSJ                   1461
#define IDPRINT                         1462
#define IDSWITCH                        1463
#define IDC_ACTIVEMOVIECONTROL1         1464
#define IDC_BUTTON_IMGCAP               1465
#define IDC_COMBO_QCYS                  1466
#define IDC_CHECK_BCBG                  1467
#define IDC_CHECK_BLUR                  1468
#define IDC_EDIT_INDEXWORD              1469
#define IDC_BUTTON_TRANSTABLE           1470
#define IDC_CHECK_ZC                    1471
#define IDC_CHECK_BD                    1472
#define IDC_CHECK_TG                    1473
#define IDC_CHECK_CQ                    1474
#define IDC_CHECK_SQ                    1475
#define IDC_CHECK_BQ                    1476
#define IDC_CHECK_MYZH                  1477
#define IDC_CHECK_FZBL                  1478
#define IDC_CHECK_DJ                    1479
#define IDC_CHECK_TSRS                  1480
#define IDC_BUTTON_ALL                  1481
#define IDC_RADIO_ZXZT1                 1482
#define IDC_CHECK_BY                    1483
#define IDC_RADIO_ZXZT2                 1484
#define IDC_CHECK_BS                    1485
#define IDC_RADIO_ZXZT3                 1486
#define IDC_CHECK_BXLQ                  1487
#define IDC_CHECK_YZLX1                 1488
#define IDC_CHECK_YZLX2                 1489
#define IDC_CHECK_YZLX3                 1490
#define IDC_CHECK_YZLX4                 1491
#define IDC_CHECK_YZLX5                 1492
#define IDC_CHECK_YZLX6                 1493
#define IDC_CHECK_YZLX7                 1494
#define IDC_CHECK_MODE                  1495
#define IDC_CHECK_HZJL                  1496
#define IDC_MAX_BDH                     1497
#define IDC_CHECK_RECORDFMT             1498
#define IDC_CHECK_CURYEAR               1499
#define IDC_CHECK_BAOQIE                1500
#define IDC_CHECK_YZLX8                 1501
#define IDUP                            1502
#define IDDOWN                          1503
#define IDC_BUTTON_ZLXX                 1504
#define IDC_BUTTON_FKXX                 1505
#define IDC_BUTTON_JCXX                 1506
#define IDC_BBMC_DETAIL                 1507
#define IDCHECK                         1508
#define IDC_BUTTON_DELETETC             1509
#define IDC_BUTTON_SQDDY                1510
#define IDC_SLIDERR                     1511
#define IDC_SLIDERG                     1512
#define IDC_SLIDERB                     1513
#define IDC_SLIDERE                     1514
#define IDC_SLIDERXO                    1515
#define IDC_SLIDERYO                    1516
#define IDC_STATICR                     1517
#define IDC_STATICG                     1518
#define IDC_STATICB                     1519
#define IDC_STATICE                     1520
#define IDC_STATICXO                    1521
#define IDC_STATICYO                    1522
#define IDC_RADIO3                      1523
#define IDC_RADIO4                      1524
#define IDC_RADIO5                      1525
#define IDC_RADIO6                      1526
#define IDC_RADIO7                      1527
#define IDC_RADIO8                      1528
#define IDC_CHECK_AE                    1529
#define IDC_RADIO9                      1530
#define IDC_RADIO10                     1531
#define IDC_RADIO11                     1532
#define IDC_CHECK_FLIP                  1533
#define IDC_CHECK_RGBBGR                1534
#define IDC_COMBO_BZ                    1535
#define IDC_CHECK_ALLDB                 1536
#define IDC_CHECK_ADDBJW                1537
#define IDC_EDIT_TIMESPAN               1538
#define IDC_BUTTON_YZQR                 1539
#define ID_PREVIOUS                     1540
#define ID_NEXT                         1541
#define IDC_BUTTON_PRINTER              1542
#define IDC_CHECK_YZLX9                 1543
#define IDC_CHECK_LQ                    1544
#define IDC_STATIC_SFZT                 1545
#define IDC_CHECK_QQ                    1546
#define IDC_COMBO_SFZT                  1547
#define IDC_CHECK_YZLX10                1548
#define IDC_EDIT_QCJL                   1549
#define IDC_CHECK_YZLX11                1550
#define IDC_EDIT_LCZL                   1551
#define IDC_CHECK_YZLX12                1552
#define IDC_BUTTON_DEFAULTQUERY         1553
#define IDC_COMBO_TIMEMODE              1554
#define IDC_BUTTON_BDQUERY              1555
#define IDC_BUTTON_TD                   1556
#define IDC_STATIC_KB                   1557
#define ID_PRINT                        1558
#define ID_CAPTURE                      1559
#define IDC_DT_STARTDATE                1560
#define IDC_DT_STARTTIME                1561
#define IDC_DT_ENDDATE                  1562
#define IDC_DT_ENDTIME                  1563
#define IDC_BUTTON_TODAY                1564
#define IDC_BUTTON_YESTERDAY            1565
#define IDC_BUTTON_THREE                1566
#define IDC_BUTTON_WEEK                 1567
#define IDC_BUTTON_HZQR                 1568
#define IDC_BUTTON_BBQS                 1569
#define IDC_SENDBDYY                    1570
#define IDREJECT                        1571
#define IDC_CHECK_HEBING                1572
#define IDC_BUTTON_SEARCH               1573
#define IDC_BUTTON_SEARCH2              1574
#define IDC_BUTTON_CONFIRM              1575
#define IDC_STATIC_ZCLIST               1576
#define IDC_BUTTON_CONFIRM2             1577
#define IDC_COMBO_DEVICES               1578
#define IDC_RefreshList                 1579
#define IDC_COMBO_MODEL                 1580
#define IDC_EDIT_VERSION                1581
#define IDC_EDIT_CAMERATYPE             1582
#define IDC_EDIT_ROIPOSITION            1583
#define IDC_COMBO_SCANMODE              1584
#define IDC_COMBO_MODE                  1585
#define IDC_COMBO_CAMERATEMP            1586
#define IDC_COMBO_LOCKED                1587
#define IDC_COMBO_METERING1             1588
#define IDC_EDIT_BIAS                   1589
#define IDC_COMBO_LOCKED2               1590
#define IDC_COMBO_ISSUSPENDED           1591
#define IDC_COMBO_METERING2             1592
#define IDC_COMBO_TIME                  1593
#define IDC_EDIT_GAIN                   1594
#define IDC_ONEPUSHAE                   1595
#define IDC_EDIT_LEVELSGAIN             1596
#define IDC_EDIT_REDGAIN                1597
#define IDC_EDIT_GREENGAIN              1598
#define IDC_EDIT_BLUEGAIN               1599
#define IDC_EDIT_CONTRAST               1600
#define IDC_EDIT_SATURATION             1601
#define IDC_EDIT_REDSATURATION          1602
#define IDC_EDIT_GREENSATURATION        1603
#define IDC_EDIT_BLUESATURATION         1604
#define IDC_EDIT_TONE                   1605
#define IDC_EDIT_HUE                    1606
#define IDC_EDIT_REDBALANCE             1607
#define IDC_EDIT_GREENBALANCE           1608
#define IDC_EDIT_BLUEBALANCE            1609
#define IDC_EDIT_TONEFILE               1610
#define IDC_COMBO2                      1611
#define IDC_EXPO_COMP                   1611
#define IDC_COMBO_TONELIST              1612
#define IDC_COMBO_COLORCAST             1613
#define IDC_COMBO_NOISEREDUCTION        1614
#define IDC_EDIT_SHARPNESS              1615
#define IDC_EDIT_SHADINGCORRECTION      1616
#define IDC_COMBO_SAVESHADINGPOSITION   1617
#define IDC_BUTTON_BALANCE              1618
#define IDC_BUTTON_TONESET              1619
#define IDC_BUTTON_SHADINGDATACAPTURE   1620
#define IDC_COMBO_RESOLUTION            1621
#define IDC_COMBO_RENDER                1622
#define IDC_COMBO_SHIFT                 1623
#define IDC_COMBO_QUALITY               1624
#define IDC_COMBO_TRIGGER               1625
#define IDC_EDIT_FILEPATH               1626
#define IDC_COMBO_MTLIST                1627
#define IDC_COMBO_SHADINGLIST           1628
#define IDC_PICTURE_PREVIEW             1629
#define IDC_BUTTON_SNAPSHOT             1630
#define IDC_COMBO_PRESET2               1631
#define IDC_EDIT_PRESET                 1632
#define IDC_BUTTON_PROPLOAD             1633
#define IDC_BUTTON_PROPSAVE             1634
#define IDC_EDIT_WINDOW                 1635
#define IDC_EDIT_WINDOW2                1636
#define IDC_EDIT_WINDOW3                1637
#define IDC_EDIT_WINDOW4                1638
#define IDC_RADIO_APPADD                1639
#define IDC_BUTTON_WINDOWHANDLE         1640
#define IDC_BUTTON_CONTINUOUSSHOT       1641
#define IDC_RADIO_APPREMOVE             1642
#define IDC_BUTTON_FOCUSSET             1643
#define IDC_BUTTON_MTSET                1644
#define IDC_BUTTON_SHADINGSET           1645
#define IDC_BUTTON_SNAPSHOTEX           1646
#define IDC_BUTTON_SHIFTSNAP            1647
#define IDC_BUTTON_RAWSNAP              1648
#define IDC_SPIN_FOCUSX                 1649
#define IDC_SPIN_FOCUSY                 1650
#define IDC_SPIN_FOCUSW                 1651
#define IDC_SPIN_FOCUSH                 1652
#define IDC_SPIN_MTX                    1653
#define IDC_SPIN_MTY                    1654
#define IDC_SPIN_MTW                    1655
#define IDC_SPIN_MTH                    1656
#define IDC_EDIT_INTERVAL               1657
#define IDC_EDIT_COUNT                  1658
#define IDC_BUTTON_ZC                   1659
#define IDC_STATIC_YQJL                 1660
#define IDC_BUTTON_CLOSE                1661
#define ID_INPUT_OK                     1662
#define IDC_INPUT                       1663
#define ID_INPUT_CANCEL                 1664
#define IDC_BUTTON_LY                   1665
#define IDC_BUTTON_BOOKING              1666
#define IDC_LINK_LY                     1668
#define IDC_LINK_BDYY                   1669
#define IDC_STATIC_COUNTLY              1670
#define IDC_STATIC_BDXXTIP              1671
#define IDC_EDIT_QPSMBATCH              1672
#define IDC_STATIC_SHOOTING_MODE        1672
#define IDC_EDIT_QCYZBZ                 1673
#define IDC_STATIC_EXPO_COMP            1673
#define IDC_BUTTON_OK                   1674
#define IDC_STATIC_FLASH                1674
#define IDC_LINK_ADVICE                 1675
#define IDC_STATIC_ISO_SPEED            1675
#define IDC_STATIC_ADVICETIP            1676
#define IDC_STATIC_PHOTO_EFFECT         1676
#define IDC_STATIC_TGTip                1677
#define IDC_STATIC_PHOTO_QUALITY        1677
#define IDC_BUTTON_ADVICEDEL            1678
#define IDC_STATIC_PHOTO_SIZE           1678
#define IDC_EDIT_DELREASON              1679
#define IDC_STATIC_RELEASE_PARAM        1679
#define IDC_COMBO_FontOneLine           1680
#define IDC_VIEWIMG                     1680
#define IDC_EDIT_FirstLineText          1681
#define IDC_AEAF                        1681
#define IDC_EDIT_BeginIndex             1682
#define IDC_SLIDERF                     1682
#define IDC_COMBO_FontFirstLine         1683
#define IDC_RELEASE                     1683
#define IDC_COMBO_FontSecondLine        1684
#define IDC_STATIC_RELEASE_COMMAND      1684
#define IDC_RADIO_OneLineMode           1685
#define IDC_SHOOTING_MODE               1685
#define IDC_RADIO_TwoLineMode           1686
#define IDC_FLASH                       1686
#define IDC_BUTTON_MicroWriterPrint     1687
#define IDC_ISO_SPEED                   1687
#define IDC_COMBO_GROUP                 1688
#define IDC_PHOTO_EFFECT                1688
#define IDC_STATIC_WAXINM               1689
#define IDC_PHOTO_QUALITY               1689
#define IDC_BUTTON_COPYCZ               1690
#define IDC_PHOTO_SIZE                  1690
#define IDC_EDIT_LKBS                   1691
#define IDC_PROGRESS                    1692
#define IDC_DATETIMEPICKER_MCYJ         1694
#define IDC_HISID1_EXTRACT              1697
#define ID_NOTE_QCMX                    11111
#define ID_INDICATOR_LOGO               32772
#define ID_CHOICE_SELECT                32773
#define ID_APP_CAMERA                   32774
#define ID_SHOW                         32775
#define ID_SELPRINTER                   32776
#define ID_BACKCOLOR                    32777
#define ID_DBLIST_STATE1                32778
#define ID_UNSELECTTEXT                 32779
#define ID_DBLIST_STATE2                32780
#define ID_DBLIST_STATE3                32781
#define ID_SELECTTEXT                   32782
#define ID_DBLIST_STATE5                32783
#define ID_SELECTCHOICE                 32784
#define ID_YEAR                         32785
#define ID_UNSELECTCHOICE               32786
#define ID_TIME                         32787
#define ID_DBLIST_STATE0                32788
#define ID_VIEW_MEDLIST                 32789
#define ID_CHARGEITEM_NEW               32790
#define ID_CHARGEITEM_DELETE            32791
#define ID_CHARGEITEM_ALLITEM           32792
#define ID_FIELD_NOTIFICATION           32793
#define ID_TREE_ADD                     32794
#define ID_TREE_DELETE                  32795
#define ID_TREE_MODIFY                  32796
#define ID_TREE_IMAGESHOW               32797
#define ID_TREE_IMAGEINPUT              32798
#define ID_TREE_HIDEEMPTY               32799
#define ID_SEG_SELECT                   32800
#define ID_MAINTANCE_REPORT             32801
#define ID_REPORT_DISCRIBE              32802
#define ID_REPORT_REGION                32803
#define ID_REPORT_DIA                   32804
#define ID_REPORT_RYSJ                  32805
#define ID_FILE_SYSSETUP                32806
#define ID_ACQUIRE                      32807
#define ID_SELECT_SOURCE                32808
#define ID_FO_DRAW_USERPOINT            32809
#define ID_USER_DELETE                  32810
#define ID_SETUP_TAG                    32811
#define ID_IMG_CAPTURESTP               32812
#define ID_PIC_ROTATE                   32813
#define ID_PIC_MIRROR                   32814
#define ID_PIC_FUSION                   32815
#define ID_PIC_RESAMPLE                 32816
#define ID_IMG_CAPTURE_FORMAT           32817
#define ID_IMAGEPS_COLORRECTIFY         32818
#define ID_EDIT_MAGIC                   32819
#define ID_AREAGROW                     32820
#define ID_VALUE_ADD                    32821
#define ID_VALUE_DELETE                 32822
#define ID_AOI_REFER                    32823
#define ID_AOI_CUT                      32824
#define ID_IMAGE_MARK                   32825
#define ID_IMAGE_CUT                    32826
#define ID_IMAGE_COPY                   32827
#define ID_IMAGE_PASTE                  32828
#define ID_IMAGE_SAVE                   32829
#define ID_IMAGE_RECTIFY                32830
#define ID_PIC_NOTE                     32831
#define ID_PIC_OUTPUT                   32832
#define ID_LINETYPE_SELECT              32833
#define ID_TEXTTYPE_SELECT              32834
#define ID_RULERMARK                    32835
#define ID_VIEW_OUTPUT                  32836
#define ID_STANDARD_VIEW                32837
#define ID_STANDARD_ADD                 32838
#define ID_APP_LAST                     32839
#define ID_APP_NEXT                     32840
#define ID_APP_CHECK                    32841
#define ID_APP_SEND                     32842
#define ID_APP_COLLECT                  32843
#define ID_APP_LOGOUT                   32844
#define ID_USER_MODIFY                  32845
#define ID_DOC_CLOSE                    32846
#define ID_FILE_INPUT                   32847
#define ID_FILE_OUTPUT                  32848
#define ID_FILE_MAIL                    32849
#define ID_APP_DBSELECT                 32850
#define ID_DOC_SAVEAS                   32851
#define ID_DOC_MANAGER                  32852
#define ID_USER_4                       32853
#define ID_FILE_SECURITYSETUP           32854
#define ID_USER_1                       32855
#define ID_USER_2                       32856
#define ID_USER_3                       32857
#define ID_APP_REFRESH                  32858
#define ID_DBLIST_STATE4                32859
#define ID_FILE_RPTMODIFY               32860
#define ID_APP_GETCODE                  32861
#define ID_APP_UNCHECK                  32862
#define ID_USER_GEN                     32863
#define ID_PIC_EXCHANGE                 32864
#define ID_PIC_PRINT                    32865
#define ID_PIC_UNPRINT                  32866
#define ID_PIC_SAVEAS                   32867
#define ID_REFERENCE                    32868
#define ID_DH_SETUP                     32869
#define ID_DH_WB                        32870
#define ID_DH_GAMMA                     32871
#define ID_DH_CANCELGAMMA               32872
#define ID_DH_MODE0                     32873
#define ID_DH_MODE1                     32874
#define ID_DH_MODE2                     32875
#define ID_DH_CONVERSION_GB             32876
#define ID_DH_CONVERSION_GR             32877
#define ID_DH_CONVERSION_BG             32878
#define ID_DH_CONVERSION_RG             32879
#define ID_MAINTANCE_SELFFIELD          32880
#define ID_DOC_NEWORDER                 32881
#define ID_DOC_QUICKINPUT               32882
#define ID_DBLIST_STATE6                32883
#define ID_DOC_LOGO                     32884
#define ID_APP_NOTEPAD                  32885
#define ID_FILE_RPTCOPY                 32886
#define ID_FILE_DBSETUP                 32887
#define ID_DOC_QUERY                    32888
#define ID_LOC_PRINT_PREVIEW            32889
#define ID_LOC_PRINT                    32890
#define ID_ZPGL_CKYJ                    32893
#define ID_ZPGL_QPYJ                    32894
#define ID_ZPGL_YZDY                    32895
#define ID_ZPGL_ZPQKTJ                  32896
#define ID_FILE_RPTCOPYALL              32897
#define ID_MAINTANCE_SELFSHOW           32898
#define ID_WDM_DEVICE                   32899
#define ID_TREE_MOVEUP                  32900
#define ID_TREE_MOVEDOWN                32901
#define ID_DATESEL                      32902
#define ID_FULLSCREEN                   32903
#define ID_FILE_RPTCOPYIMG              32904
#define ID_IMG_OLYMPUS                  32905
#define ID_ZPGL_SFQR                    32906
#define ID_ZPGL_CGSFQR                  32907
#define ID_FILE_RPTVIEW                 32908
#define ID_REPORT_VIEW                  32909
#define ID_REPORT_BLH                   32910
#define ID_REPORT_PREVIOUS              32911
#define ID_REPORT_NEXT                  32912
#define ID_REPORT_FORMAT                32913
#define ID_REPORT_SEND                  32914
#define ID_REPORT_OUTPUT                32915
#define ID_ZPGL_ZCSFQR                  32916
#define ID_YQBG                         32917
#define ID_BBMC                         32918
#define ID_BDJG                         32919
#define ID_COPY_RYSJ                    32920
#define ID_COPY_GJSJ                    32921
#define ID_COPY_ZDYJ                    32922
#define ID_REPORT_CHECK                 32923
#define IDM_BATCHUPADATE                32924
#define IDM_MATEARIAL_YZ                32928
#define ID_INSERT_BSZY                  32931
#define ID_INSERT_RYSJ                  32932
#define ID_INSERT_ZDYJ                  32933
#define ID_MAINTENANCE_PICNOTE          32938
#define ID_REPORT_PRINT                 32939
#define ID_REPORT_SELPIC                32940
#define IDM_MATEARIAL_WriterPrint       32944
#define IDM_MATEARIAL_SelAll            32945
#define ID_WRITER_PRINT_SETUP           32946
#define IDM_MATEARIAL_LKBS              32947
#define IDM_MATEARIAL_EMBEDBOXPRINT     32951
#define ID_DOC_NEWORDER1                 32952

#define ID_INDICATOR_BGZT               51446
#define ID_INDICATOR_BGDY               51447
#define ID_APP_DZBL                     51448
#define ID_NOTE_1                       51449

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        336
#define _APS_NEXT_COMMAND_VALUE         32953
#define _APS_NEXT_CONTROL_VALUE         1698
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
