#if !defined(AFX_VIDEOFORMATS1_H__21E9525E_CD93_42F9_8F3C_177C7DF4CC17__INCLUDED_)
#define AFX_VIDEOFORMATS1_H__21E9525E_CD93_42F9_8F3C_177C7DF4CC17__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVideoFormats wrapper class

class CVideoFormats : public COleDispatchDriver
{
public:
	CVideoFormats() {}		// Calls COleDispatchDriver default constructor
	CVideoFormats(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVideoFormats(const CVideoFormats& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	LPDISPATCH GetItem(const VARIANT& Key);
	short FindVideoFormat(LPCTSTR strVideoFormat);
	long FindVideoFormatHeight(short index);
	long FindVideoFormatWidth(short index);
	CString FindVideoFormatName(short index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIDEOFORMATS1_H__21E9525E_CD93_42F9_8F3C_177C7DF4CC17__INCLUDED_)
