#if !defined(AFX_VIDEOINPUTS1_H__7CDA1AC7_E2B2_45E2_AEA4_04D8CB2D4F43__INCLUDED_)
#define AFX_VIDEOINPUTS1_H__7CDA1AC7_E2B2_45E2_AEA4_04D8CB2D4F43__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CVideoInputs wrapper class

class CVideoInputs : public COleDispatchDriver
{
public:
	CVideoInputs() {}		// Calls COleDispatchDriver default constructor
	CVideoInputs(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CVideoInputs(const CVideoInputs& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	short GetCount();
	void SetCount(short);

// Operations
public:
	LPDISPATCH GetItem(const VARIANT& Key);
	short FindVideoInput(LPCTSTR strVideoInput);
	CString FindVideoInputName(short index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIDEOINPUTS1_H__7CDA1AC7_E2B2_45E2_AEA4_04D8CB2D4F43__INCLUDED_)
